"""add permissions to user

Revision ID: 35c89fad7549
Revises: ad1c5f109f8e
Create Date: 2026-02-05 11:35:39.778476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c89fad7549'
down_revision: Union[str, None] = 'ad1c5f109f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', sa.Text(), nullable=True))
    # op.alter_column('users', 'last_password_change',
    #            existing_type=sa.TIMESTAMP(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_password_change',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
