"""add security fields to user

Revision ID: ad1c5f109f8e
Revises: fd1dae29c372
Create Date: 2026-02-05 11:13:33.174114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1c5f109f8e'
down_revision: Union[str, None] = 'fd1dae29c372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_password_change', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_change')
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
