"""add duration and tags to module

Revision ID: b067204ca9a1
Revises: a3d9b673e152
Create Date: 2026-02-04 10:08:46.130439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b067204ca9a1'
down_revision: Union[str, None] = 'a3d9b673e152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('modules', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'tags')
    op.drop_column('modules', 'duration')
    # ### end Alembic commands ###
